### PR TITLE
[FIX] Slightly improved file_matches if same name & path

### PR DESCRIPTION
**Pull request by raiseandfall**
Hi @brainshave 

I slightly improved the file_matches in case the name & path are fully equal. I had the case in one project.
Let me know if that works.

Thanks !

### CODE REVIEW

**Comment by szymonrw** [comment]
Good catch! :smiley: 

Again I took to an excuse to improve it a bit and I took `find_closest_match` to a separate file and unit-tested it. Then it turned out (correct me if I'm wrong) that the `is_directory` check is not needed anymore with your patch.

Feel free to add more unit tests, there are probably cases I haven't thought about.

Cheers!

**Comment by raiseandfall** [comment]
Thanks, looks good :+1: 
It works on the specific project.

Can you publish 2.0.3 to npm ? Thanks !

**Comment by szymonrw** [comment]
Thought I already done this, thanks for pointing it out!

**Comment by raiseandfall** [comment]
Awesome thanks !

**Pull request merged**
